### ISSUE TITLE
dynamic pod env can't pass-through to Leaf cluster

### ISSUE THREAD

**Issue by village-way** [kosmos-io/kosmos#509]
**What happened**:

When Kafka statefulset resources are orchestrated across clusters using Kosmos, they utilize dynamic environment variables, such as obtaining the nodeName of the current pod. However, in the current version of Kosmos, when pods are dispatched to leaf clusters, they are assigned virtual node names instead of the actual leaf cluster node names. This discrepancy leads to operational issues with the pods.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: kosmos-kafka
      tolerations:
        - key: kosmos.io/node
          operator: Equal
          value: "true"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JMX_PORT
              value: "9999"
            - name: NODEIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PODIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: IS_KAFKA_FROZEN
              value: "false"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms8192 -Xmx8192M"
            - name: LOG_DIRS
              value: "/kafka/data-0"
```

**What you expected to happen**:
the pod should get the real env 

**How to reproduce it (as minimally and precisely as possible)**:

<img width="439" alt="image" src="https://github.com/kosmos-io/kosmos/assets/11625846/bf998346-5331-4772-a860-b0f7db9de3cb">

**Anything else we need to know?**:

**Environment**:
- Kosmos version:
- Others:
